### ISSUE TITLE
Making segway_rmp node robust to extremely high odometry changes

### ISSUE THREAD

**Issue by piyushk** [segwayrmp/segway_rmp#26]
One of our segway bases seems to be failing, and intermittently reports high jumps in odometry. I'm not sure if it is worth it, but it might make sense to add some safeguards in the code to detect and negate high odom jumps in 1 cycle.

**Comment by wjwwood** [comment]
@piyushk, just my 2-cents, the segway node should never filter output from the segway. If the spike is due to an error in the node it should be fixed, and if it is data from segway that is spiking for some reason then it should be reported as such. Any filtering should happen outside the node because otherwise it might affect results for someone who isn't aware of the filtering or it might accidentally hide other phenomenon that you didn't intend to suppress.

**Comment by piyushk** [comment]
@wjwwood That sounds like a great suggestion, especially since I'm highly skeptical of introducing this change. I'll look into it implementing outside the segway_rmp code.
